
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vendaval
 */
public class VentanaCrearUniversidad extends javax.swing.JInternalFrame {
    private VentanaPrincipal ventanaPrincipal;

    /**
     * Creates new form VentanaCrearUniversidad
     */
    public VentanaCrearUniversidad(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal= ventanaPrincipal;
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        txtdenominacion = new javax.swing.JTextField();
        jbtnguardar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Datos de Universidad");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("RUC:");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel1KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DENOMINACION:");

        txtruc.setToolTipText("");
        txtruc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrucFocusLost(evt);
            }
        });
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrucKeyTyped(evt);
            }
        });

        txtdenominacion.setToolTipText("");
        txtdenominacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdenominacionActionPerformed(evt);
            }
        });
        txtdenominacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdenominacionKeyTyped(evt);
            }
        });

        jbtnguardar.setText("GUARDAR");
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtruc))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jbtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdenominacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdenominacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdenominacionActionPerformed

    private void txtrucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrucFocusLost
        // TODO add your handling code here:
        String ruc;
        Universidad universidad;
        Reporte r;
        r = ventanaPrincipal.getReporte();
        
    if(txtruc.getText().length()!=0){    
        ruc = String.valueOf(txtruc.getText());
        universidad = r.buscarUniversidad(ruc);
            if(universidad != null){
                    JOptionPane.showMessageDialog(this, "La Universidad con ruc "+ruc+" ya está registrada");
                        txtruc.setText("");
                        }
    }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese RUC");
            }
                            
                          
                           
    }//GEN-LAST:event_txtrucFocusLost

    private void txtdenominacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdenominacionKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
    }//GEN-LAST:event_txtdenominacionKeyTyped

    private void txtrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyTyped
        // TODO add your handling code here:
       /* char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }*/
    }//GEN-LAST:event_txtrucKeyTyped

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed
        // TODO add your handling code here:
        String ruc;
        String denominacion;
        Universidad universidad;
        Reporte r=ventanaPrincipal.getReporte();
        if(txtruc.getText().length()!=0){ 
            ruc = String.valueOf(txtruc.getText());
            universidad = r.buscarUniversidad(ruc);
             if(universidad == null){
             denominacion = txtdenominacion.getText();
             universidad = new Universidad(denominacion, ruc);                                  
             r.agregarUniversidad(universidad);
             JOptionPane.showMessageDialog(this, "Se registro los datos");
            txtruc.setText("");
            txtdenominacion.setText("");
            
            universidad.setFacultad(new Facultad("DERECHO")); 
            universidad.setFacultad(new Facultad("CIENCIAS FISICAS Y MATEMATICAS"));
            universidad.setFacultad(new Facultad("CIENCIAS SOCIALES"));
            universidad.setFacultad(new Facultad("CIENCIAS ECONOMICAS"));
            this.ventanaPrincipal.AgregarUniversidad(universidad);
        }else{
            JOptionPane.showMessageDialog(this, "El ruc ya esta registrado");
            txtruc.setText("");
        }
        }
    }//GEN-LAST:event_jbtnguardarActionPerformed

    private void jLabel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JTextField txtdenominacion;
    private javax.swing.JTextField txtruc;
    // End of variables declaration//GEN-END:variables
}
