
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JOptionPane;


public class VentanaMatricularAlumno extends javax.swing.JInternalFrame {
    private VentanaPrincipal ventanaPrincipal;
    private VentanaCrearUniversidad ventanaCrearUniversidad;
    private Universidad u;
    private HashSet<Universidad> uni= new HashSet<Universidad>();

    /**
     * Creates new form VentanaMatricularAlumno
     */
    public VentanaMatricularAlumno(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal= ventanaPrincipal;
        this.ventanaCrearUniversidad  = ventanaCrearUniversidad;
    }
    public void guardarUniversidad(HashSet<Universidad> uni){
        this.uni=uni;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultad = new javax.swing.JLabel();
        verificarRuc2 = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfacultad = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtruc = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcodigo = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtnombre = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtcelular = new javax.swing.JTextPane();
        btnguardar2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Matricular Alumno");
        setVisible(true);

        facultad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        facultad.setText("Facultad:");

        verificarRuc2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        verificarRuc2.setText("Buscar RUC:");
        verificarRuc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarRuc2KeyTyped(evt);
            }
        });

        codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigo.setText("Código:");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.setText("Nombre:");

        celular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        celular.setText("Celular:");

        txtfacultad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfacultadKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtfacultad);

        txtruc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrucFocusLost(evt);
            }
        });
        txtruc.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtrucInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrucKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtruc);

        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtcodigo);

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtnombre);

        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelularKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(txtcelular);

        btnguardar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnguardar2.setText("GUARDAR");
        btnguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verificarRuc2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnguardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(verificarRuc2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnguardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificarRuc2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarRuc2KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_verificarRuc2KeyTyped

    private void txtrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtrucKeyTyped

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtcelularKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtfacultadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfacultadKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
    }//GEN-LAST:event_txtfacultadKeyTyped

    private void txtrucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrucFocusLost
        // TODO add your handling code here:
         String ruc;
        Universidad universidad;
        Reporte r;
        r = ventanaPrincipal.getReporte();
        
    if(txtruc.getText().length()!=0){    
        ruc = String.valueOf(txtruc.getText());
        universidad = r.buscarUniversidad(ruc);
            if(universidad != null){
                    JOptionPane.showMessageDialog(this, "La Universidad con ruc "+ruc+" se registro");
                        }
    }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese RUC");
            }
                  
                        
    }//GEN-LAST:event_txtrucFocusLost

    private void btnguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar2ActionPerformed
      
        String ruc;
        String codigo;
        String nombre;
        String celular;
        String nombrefacultad;
        Universidad universidad;
        Facultad facultad;
        boolean encontrado=false;
        
    if(txtruc.getText().length()!=0){    
        ruc = String.valueOf(txtruc.getText());
        Iterator<Universidad> iterador = uni.iterator();
        while(iterador.hasNext() && encontrado == false){
            universidad = iterador.next();
            if(ruc.equals(universidad.getRuc())){
                encontrado = true;
                codigo= txtcodigo.getText();
                nombre=txtnombre.getText();
                celular=txtcelular.getText();
                nombrefacultad=txtfacultad.getText();
                Alumno al=new Alumno(nombre,codigo,celular, universidad);
                //Facultad fa=new Facultad(nombrefacultad);
                System.out.println(al.getNombre());
                universidad.matricular(al);
                facultad=universidad.buscarFacultad(nombrefacultad);
                if(facultad!=null){
                    universidad.matricular(al);
                    al.setFacultad(facultad);
                }
                JOptionPane.showMessageDialog(this, "Se registro los datos");
            txtruc.setText("");
            txtnombre.setText("");
            txtcelular.setText("");
            txtcodigo.setText("");
            txtfacultad.setText("");
                //System.out.println(universidad.obtenerDatosDelAlumno());
            }
        
        }
    }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese RUC");
            }
                  
    }//GEN-LAST:event_btnguardar2ActionPerformed

    private void txtrucInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtrucInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrucInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar2;
    private javax.swing.JLabel celular;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel facultad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextPane txtcelular;
    private javax.swing.JTextPane txtcodigo;
    private javax.swing.JTextPane txtfacultad;
    private javax.swing.JTextPane txtnombre;
    private javax.swing.JTextPane txtruc;
    private javax.swing.JLabel verificarRuc2;
    // End of variables declaration//GEN-END:variables
}
