
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class VentanaDatosdeUniversidad extends javax.swing.JInternalFrame {
    private VentanaPrincipal ventanaPrincipal;

    /**
     * Creates new form VentanaDatosdeUniversidad
     */
    public VentanaDatosdeUniversidad(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        mostrarDatos();
    }
    public void mostrarDatos(){
         Universidad uni;
        Object[] datos = new Object[2];
        Reporte r = ventanaPrincipal.getReporte();
        Iterator<Universidad> iterator = r.getIterator();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("RUC");
        modelo.addColumn("Denominación");
        
        while(iterator.hasNext()){
            uni = iterator.next();
            datos[0] = uni.getRuc();
            datos[1] = uni.getDenominacion();
            modelo.addRow(datos);
        }
        
        tblUniversidades.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUniversidades = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Datos de las Universidades");
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUniversidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUniversidades);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        mostrarDatos();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUniversidades;
    // End of variables declaration//GEN-END:variables
}
