
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class VentanaDatosDeAlumnos extends javax.swing.JInternalFrame {
    private VentanaPrincipal ventanaPrincipal; 
    private HashSet<Universidad> uni= new HashSet<Universidad>();

    /**
     * Creates new form VentanaDatosDeAlumnos
     */
    public VentanaDatosDeAlumnos(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
    }
    public void guardarUniversidad(HashSet<Universidad> uni){
        this.uni=uni;
        mostrarDatos();
    }
    public void mostrarDatos(){
         String ruc=JOptionPane.showInputDialog("Ingresar Ruc: ");  
        Alumno a;
        Universidad universidad;
        boolean encontrado=false;
        DefaultTableModel modelo = new DefaultTableModel();
        
        
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Celular");
        modelo.addColumn("Facultad");
        HashSet<Alumno> alumnos = new HashSet<Alumno>();
        Object[] datos = new Object[4];
        Iterator<Universidad> iterador = uni.iterator();
        while(iterador.hasNext() && encontrado == false){
            universidad = iterador.next();
            if(ruc.equals(universidad.getRuc())){
                  System.out.println(universidad.getRuc());
                encontrado = true;
                System.out.println(universidad.obtenerDatosDelAlumno()
                );
                alumnos = universidad.getAlumnos();
                System.out.println(universidad.getRuc()
                );
            }
            }
            if(alumnos != null){
              Iterator<Alumno> iterator = alumnos.iterator();
            while(iterator.hasNext()){
            a = iterator.next();
            datos[0] = a.getCodigo();
            System.out.println(a.getCodigo());
            datos[1] = a.getNombre();
            System.out.println(a.getNombre());
            datos[2] = a.getCelular();
            System.out.println(a.getCelular());
            datos[3] = a.getFacultad();
            System.out.println(a.getFacultad());
            modelo.addRow(datos);
            }
            }
            
     
        
        tblalumnos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblalumnos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Datos de los Alumnos");
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tblalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblalumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        mostrarDatos();
         
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblalumnos;
    // End of variables declaration//GEN-END:variables
}
